platform :ios, '10.0'
use_frameworks!
inhibit_all_warnings!

abstract_target 'Shared' do

  target 'ComapiFoundationSample' do
    pod 'JWT'
  end

  target 'ComapiFoundationSample-Swift' do
    pod 'JWT'
    pod 'SnapKit'
  end
end


